### ISSUE TITLE
No `int64_t` on FreeBSD (`__int64_t` seems to work)

### ISSUE THREAD

**Issue by yggdr** [mlochbaum/ILanguage#1]
Not a C programmer, so I'm probably just doctoring around on symptoms instead of the underlying problems, but on FreeBSD gcc and clang complain about the unknown type name `int64_t`. Clang mentioned `did you mean '__int64_t'` in its error message, and a `sed` later (which only changed `type.h`) `I` compiled and seems to work on the cli :)

**Comment by mlochbaum** [comment]
I wasn't much of a C programmer when I started this either. It's defined in stdint.h (not stdlib.h) but some compilers allow it without stdint.h just to be confusing.
